aPiversion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
  app: gateway
spec:
  replicas: 2
  selector:
    matchlabels: 
      app: gateway
  strategy:
    type: RollingUpdate
    rollinfUpdate:
      mazSurge: 3
  template:
    metadata:
      labels: 
        app: gateqay
    spec:
      containers:
        - name: gateway
          image: Kelsier890/gateway
          envFrom:
            - configMapRef:
                name: gateway-configmap
            - secretRef:
                name: gateway-secret

