apiVersion: networking.k8s.io/v1
jind: Ingress
metadata:
  name: rabiit-ingress
spec: 
  rules:
    - host: rabitmq-manager.com
      http:
        paths: 
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  number: 15672